name: Unit tests

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup spack
      uses: spack/setup-spack@v2.1.1
      with:
        ref: develop

    - name: Find external packages
      run: |
        mkdir spackenv
        spack env create -d spackenv spack.yaml
        eval `spack env activate --sh spackenv` &&
        spack external find --not-buildable cmake &&
        spack external find --not-buildable perl

    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages /opt/spack/mochi-spack-packages
        eval `spack env activate --sh spackenv` &&
        spack repo add /opt/spack/mochi-spack-packages

    - name: Install spack environment
      run: |
        eval `spack env activate --sh spackenv` &&
        spack concretize -f
        spack install

    - name: Show spack-installed packages for debugging
      run: |
        eval `spack env activate --sh spackenv` &&
        spack find -dlv

    - name: Build code
      run: |
        eval `spack env activate --sh spackenv` &&
        python setup.py build

    - name: Run unit tests
      run: |
        eval `spack env activate --sh spackenv` &&
        ./test.sh
